#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParqueoWebApp.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Parqueo")]
	public partial class PaqueoWebDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertParqueo(Parqueo instance);
    partial void UpdateParqueo(Parqueo instance);
    partial void DeleteParqueo(Parqueo instance);
    #endregion
		
		public PaqueoWebDataContext() : 
				base(global::ParqueoWebApp.Properties.Settings.Default.Azure, mappingSource)
		{
			OnCreated();
		}
		
		public PaqueoWebDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PaqueoWebDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PaqueoWebDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public PaqueoWebDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Parqueo> Parqueos
		{
			get
			{
				return this.GetTable<Parqueo>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Parqueo")]
	public partial class Parqueo : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _cedula;
		
		private string _placa;
		
		private System.DateTime _fecha_entrada;
		
		private System.Nullable<System.DateTime> _fecha_salida;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OncedulaChanging(string value);
    partial void OncedulaChanged();
    partial void OnplacaChanging(string value);
    partial void OnplacaChanged();
    partial void Onfecha_entradaChanging(System.DateTime value);
    partial void Onfecha_entradaChanged();
    partial void Onfecha_salidaChanging(System.Nullable<System.DateTime> value);
    partial void Onfecha_salidaChanged();
    #endregion
		
		public Parqueo()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cedula", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string cedula
		{
			get
			{
				return this._cedula;
			}
			set
			{
				if ((this._cedula != value))
				{
					this.OncedulaChanging(value);
					this.SendPropertyChanging();
					this._cedula = value;
					this.SendPropertyChanged("cedula");
					this.OncedulaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_placa", DbType="VarChar(16) NOT NULL", CanBeNull=false)]
		public string placa
		{
			get
			{
				return this._placa;
			}
			set
			{
				if ((this._placa != value))
				{
					this.OnplacaChanging(value);
					this.SendPropertyChanging();
					this._placa = value;
					this.SendPropertyChanged("placa");
					this.OnplacaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha_entrada", DbType="Date NOT NULL")]
		public System.DateTime fecha_entrada
		{
			get
			{
				return this._fecha_entrada;
			}
			set
			{
				if ((this._fecha_entrada != value))
				{
					this.Onfecha_entradaChanging(value);
					this.SendPropertyChanging();
					this._fecha_entrada = value;
					this.SendPropertyChanged("fecha_entrada");
					this.Onfecha_entradaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fecha_salida", DbType="Date")]
		public System.Nullable<System.DateTime> fecha_salida
		{
			get
			{
				return this._fecha_salida;
			}
			set
			{
				if ((this._fecha_salida != value))
				{
					this.Onfecha_salidaChanging(value);
					this.SendPropertyChanging();
					this._fecha_salida = value;
					this.SendPropertyChanged("fecha_salida");
					this.Onfecha_salidaChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
