<?xml version="1.0" encoding="utf-8"?><Database Name="Parqueo" Class="PaqueoWebDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=jaa4ef2vub.database.windows.net;Initial Catalog=Parqueo;Persist Security Info=True;User ID=parqueo" SettingsObjectName="ParqueoWebApp.Properties.Settings" SettingsPropertyName="Azure" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Parqueo" Member="Parqueos">
    <Type Name="Parqueo">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="cedula" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="placa" Type="System.String" DbType="VarChar(16) NOT NULL" CanBeNull="false" />
      <Column Name="fecha_entrada" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="fecha_salida" Type="System.DateTime" DbType="Date" CanBeNull="true" />
    </Type>
  </Table>
</Database>